ConfigVersion: 1.2.2
#语言设置
defaultLanguage: "zh_CN"
languageMap:
  zh: "zh_CN"
  zh_HK: "zh_CN"
  zh_TW: "zh_CN"
  zh_SG: "zh_CN"
  en: "en_US"
  en_GB: "en_US"
#命令设置
cmdUser: "HuntGame"
cmdAdmin: "HuntGameAdmin"
#可以在游戏房间中使用的命令
cmdWhitelist:
  - ban
  - kick
  - report

QuitRoom:
  #退出房间执行命令
  cmd: []
#游戏结束后自动加入下一局
AutomaticNextRound: false

#玩家胜利执行命令
victoryCmd:
  - me 我胜利了
  - tell "@p" 恭喜获得胜利！&con
#玩家失败执行命令
defeatCmd:
  - me 我失败了
  - tell "@p" 再接再厉！&con

#游戏积分
integral:
  #参与游戏基础积分
  base: 100
  #安全嘲讽积分
  taunt-safe: 1
  #危险嘲讽积分
  taunt-danger: 2
  #烟花嘲讽积分
  taunt-fireworks: 3
  #闪电嘲讽积分
  taunt-lightning: 5
  #击杀猎物积分
  killPrey: 100