name: HuntGame
main: cn.lanink.huntgame.HuntGame
version: "1.0.0-PM1E"
api: ["Nukkit-PM1E"]
load: POSTWORLD
author: "LT_Name"
depend:
  - "MemoriesOfTime-GameCore"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"

permissions:
  huntgame.command.user:
    default: true
  huntgame.command.admin:
    default: op