name: HuntGame
main: cn.lanink.huntgame.HuntGame
version: "1.3.1"
api: ["1.0.9"]
load: POSTWORLD
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"

permissions:
  huntgame.command.user:
    default: true
  huntgame.command.admin:
    default: op