name: HuntGame
main: cn.lanink.huntgame.HuntGame
version: "1.3.2-NKMOT-SNAPSHOT"
api: ["Nukkit-PM1E"]
load: POSTWORLD
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"

permissions:
  huntgame.command.user:
    default: true
  huntgame.command.admin:
    default: op