name: BlockHunt
main: cn.lanink.blockhunt.BlockHunt
version: "0.0.3"
api: ["1.0.9"]
load: POSTWORLD
author: "LT_Name"
loadbefore:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"

permissions:
  blockhunt.command.user:
    default: true
  blockhunt.command.admin:
    default: op